version: "3.9"

services:
  database:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: 1
      TZ: Asia/Bangkok
    volumes:
      - database-volume:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    name : app-network

volumes:
  database-volume:
    name : database-volume
    external : false